meta_product_name: "Profil Maxence Lenoir"
meta_title: "Profil Maxence Lenoir - Développeur Full Stack"
meta_description: "Ingénieur généraliste de formation, je me lance dans le Freelance après un passage par le Bootcamp du Wagon"
meta_image: "cover.png" # should exist in `app/assets/images/`